---
name: "Build BI Base image"

on:
  push:
    branches: [master, dev]
    paths:
      - "bi/base/**"
      - ".github/workflows/bi-base.yaml"
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "bi/base/**"
      - ".github/workflows/bi-base.yaml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TZ: Asia/Shanghai
  WORK_DIR: bi/base
  DOCKERHUB_REPO: registry.cn-chengdu.aliyuncs.com/jdsgame/bi-base

jobs:
  build:
    name: "Build image"
    strategy:
      fail-fast: true
      matrix:
        include:
          - { os: ubuntu-24.04, platform: linux/amd64 }
          - { os: ubuntu-24.04-arm, platform: linux/arm64 }
    runs-on: ${{ matrix.os }}
    outputs:
      platform_pair: ${{ steps.prepare.outputs.platform_pair }}
      build_tag: ${{ steps.prepare.outputs.build_tag }}

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: "Prepare"
        id: prepare
        run: |
          PLATFORM_PAIR="$(awk -F/ '{print $1"-"$2$3}' <<< "${{ matrix.platform }}")"
          TAG="$(awk -F. '{printf("%d.%d.%d", substr($1,3), $2, $3)}' <<< "$(date +%Y.%m.%d)")"
          echo "platform_pair=$PLATFORM_PAIR" >> "$GITHUB_OUTPUT"
          echo "build_tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Login to DockerHub"
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: registry.cn-chengdu.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: "Docker metadata"
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_REPO }}
          tags: type=raw,value=${{ steps.prepare.outputs.build_tag }}

      - name: "Build image"
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.WORK_DIR }}
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: >
            type=image,name=${{ env.DOCKERHUB_REPO }},
            push-by-digest=${{ github.ref_name == 'master' }},
            name-canonical=${{ github.ref_name == 'master' }},
            push=${{ github.ref_name == 'master' }}

      - name: "Export digest"
        if: github.ref_name == 'master'
        run: |
          rm -rf /tmp/digests
          mkdir -p /tmp/digests
          digest=${{ steps.build.outputs.digest }}
          touch /tmp/digests/${digest#sha256:}

      - name: "Upload artifact"
        if: github.ref_name == 'master'
        uses: actions/upload-artifact@v6
        with:
          name: digest-${{ steps.prepare.outputs.platform_pair }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    name: "Merge manifest"
    runs-on: ubuntu-latest
    if: github.ref_name == 'master'
    needs: [build]

    steps:
      - name: "Download digests"
        uses: actions/download-artifact@v7
        with:
          path: /tmp/digests
          pattern: digest-*
          merge-multiple: true

      - name: "Setup Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Login to DockerHub"
        uses: docker/login-action@v3
        with:
          registry: registry.cn-chengdu.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: "Docker metadata"
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_REPO }}
          tags: type=raw,value=${{ steps.build.outputs.build_tag }}

      - name: "Create manifest list and push"
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create \
            $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.DOCKERHUB_REPO }}@sha256:%s ' *)

      - name: "Inspect image"
        run: docker buildx imagetools inspect ${{ env.DOCKERHUB_REPO }}:${{ needs.build.outputs.build_tag }}
