---
name: "Build BI Base image"

on:
  push:
    branches: [master, dev]
    paths:
      - "bi/base/**"
      - ".github/workflows/bi-base.yaml"
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "bi/base/**"
      - ".github/workflows/bi-base.yaml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "Build image"
    runs-on: ubuntu-latest
    env:
      WORK_DIR: bi/base
      DOCKERHUB_REPO: registry.cn-chengdu.aliyuncs.com/jdsgame/bi-base

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: "Prepare tags"
        id: version
        run: tag="$(awk -F. '{printf("%d.%d.%d", substr($1,3), $2, $3)}' <<< "$(date +%Y.%m.%d)")"

      - name: "Set up Docker QEMU"
        uses: docker/setup-qemu-action@v3

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Login to DockerHub"
        uses: docker/login-action@v3
        if: github.event_name != 'pull_request'
        with:
          registry: registry.cn-chengdu.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: "Docker metadata"
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_REPO }}
          tags: type=raw,value=${{ steps.version.outputs.tag }}

      - name: "Build image"
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.WORK_DIR }}
          platforms: >
            linux/amd64
            linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.ref_name == 'master' }}
