---
name: "Dependabot merge"

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  dependabot:
    name: "Dependabot merge"
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
    permissions:
      pull-requests: read

    steps:
      # - name: "Fetch Dependabot metadata"
      #   uses: dependabot/fetch-metadata@v2
      #   with:
      #     github-token: ${{ github.token }}

      - name: "Approve and Auto-merge"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --squash --auto "$PR_URL"
