name: "Dev"

on:
  workflow_dispatch:

jobs:
  dev:
    name: "Dev"
    runs-on: ubuntu-latest

    steps:
      - run: |
          set -x
          echo "HOME=$HOME"
          echo "github.ref=${{ github.ref }}"
          echo "default_branch=${{ github.event.repository.default_branch }}"
          echo $GITHUB_ACTIONS
          echo $GITHUB_WORKSPACE
