---
name: "NextTrace CI"

on:
  push:
    branches:
      - "*"
    paths:
      - "nxtrace.sh"
      - ".github/workflows/nxtrace.yaml"
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "nxtrace.sh"
      - ".github/workflows/nxtrace.yaml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    name: "NextTrace install"
    strategy:
      fail-fast: false
      matrix:
        os:
          # debian
          - debian:bookworm # 12
          - debian:trixie # 13
          - debian:forky # 14
          - debian:sid
          # ubuntu
          - ubuntu:jammy # 22.04
          - ubuntu:noble # 24.04
          - ubuntu:plucky # 25.04
          - ubuntu:rolling
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.os }}

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Install dependencies"
        shell: bash
        run: |
          set -x
          _exists() {
            command -v "$@" > /dev/null 2>&1
          }

          install_pkg() {
            for pkg in "$@"; do
              if _exists dnf; then
                dnf install -y --allowerasing "$pkg"
              elif _exists yum; then
                yum install -y "$pkg"
              elif _exists apt-get; then
                DEBIAN_FRONTEND=noninteractive apt-get update
                DEBIAN_FRONTEND=noninteractive apt-get install -y -q "$pkg"
              fi
            done
          }

          install_pkg bash curl

      - name: "Run NextTrace install"
        run: |
          set -x
          bash nxtrace.sh
          bash nxtrace.sh --channel stable --debug --version v1.5.0
          bash nxtrace.sh --channel dev --debug --version v1.5.0
