---
name: "Shellcheck"

on:
  push:
    branches:
      - "*"
    paths:
      - "**/*.sh"
      - ".github/workflows/shellcheck.yaml"
  pull_request:
    paths:
      - "**/*.sh"
      - ".github/workflows/shellcheck.yaml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  shellcheck:
    name: "Run shellcheck"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v1

      - name: "Run shellcheck"
        uses: luizm/action-sh-checker@master
        env:
          SHFMT_OPTS: -i 4 -sr
