---
name: "Build Subscan"

on:
  push:
    branches: ["*"]
    paths:
      - "evil/subscan/**"
      - "!evil/subscan/**/*.md"
      - ".github/workflows/subscan.yaml"
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "evil/subscan/**"
      - "!evil/subscan/**/*.md"
      - ".github/workflows/subscan.yaml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "Build Subscan"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v6

      - name: "Setup Python"
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: "Install dependencies"
        working-directory: /evil/subscan
        run: |
          timedatectl set-timezone "Asia/Shanghai"
          python3 -m pip install --no-cache-dir -r requirements.txt

      - name: "Run Subscan"
        working-directory: /evil/subscan
        run: ./main.py
